#!/usr/bin/env bash
set -euo pipefail

VULKAN_VERSION=1.4.321.1
VULKAN_SHA256=f22a3625bd4d7a32e7a0d926ace16d5278c149e938dac63cecc00537626cbf73
ARCHIVE="/tmp/vulkansdk-linux-x86_64-${VULKAN_VERSION}.tar.xz"
SDK_ROOT="$HOME/vulkan-sdk"
SDK="$SDK_ROOT/${VULKAN_VERSION}/x86_64"

if [[ -s "$ARCHIVE" ]] && ! echo "${VULKAN_SHA256}  ${ARCHIVE}" | sha256sum -c - >/dev/null 2>&1; then
  rm -f "$ARCHIVE"
fi

if [[ ! -s "$ARCHIVE" ]]; then
  curl -fL --retry 5 --retry-all-errors --connect-timeout 20 --max-time 1800 \
    -o "${ARCHIVE}.part" \
    "https://sdk.lunarg.com/sdk/download/${VULKAN_VERSION}/linux/vulkansdk-linux-x86_64-${VULKAN_VERSION}.tar.xz"
  echo "${VULKAN_SHA256}  ${ARCHIVE}.part" | sha256sum -c -
  mv -f "${ARCHIVE}.part" "$ARCHIVE"
fi

echo "${VULKAN_SHA256}  ${ARCHIVE}" | sha256sum -c -

if [[ ! -x "$SDK/bin/glslc" ]]; then
  rm -rf "$SDK_ROOT"
  mkdir -p "$SDK_ROOT"
  tar -xf "$ARCHIVE" -C "$SDK_ROOT"
fi

test -x "$SDK/bin/glslc"
export VULKAN_SDK="$SDK"
export PATH="$VULKAN_SDK/bin:$PATH"
export LD_LIBRARY_PATH="$VULKAN_SDK/lib:${LD_LIBRARY_PATH:-}"

# llama.cpp requires the SPIRV-Headers CMake package. The Linux Vulkan SDK
# archive contains the SPIR-V headers, but this SDK revision does not ship a
# discoverable SPIRV-HeadersConfig.cmake. Create the minimal official package
# target locally, pointing at the SDK's immutable headers. No unpinned network
# dependency or distro package is needed.
SPIRV_INCLUDE_DIR="$VULKAN_SDK/include"
SPIRV_HEADERS_DIR="$VULKAN_SDK/share/cmake/SPIRV-Headers"

if [[ ! -f "$SPIRV_INCLUDE_DIR/spirv/unified1/spirv.hpp" ]]; then
  echo "ERROR: Vulkan SDK is missing SPIR-V headers at $SPIRV_INCLUDE_DIR/spirv/unified1/spirv.hpp" >&2
  exit 1
fi

mkdir -p "$SPIRV_HEADERS_DIR"
cat > "$SPIRV_HEADERS_DIR/SPIRV-HeadersConfig.cmake" <<EOF
# Generated by ai-chat-test/ci/prepare-vulkan.sh for llama.cpp.
# SPIRV-Headers is header-only; the Vulkan SDK provides the canonical headers.
if(NOT TARGET SPIRV-Headers::SPIRV-Headers)
  add_library(SPIRV-Headers::SPIRV-Headers INTERFACE IMPORTED)
  set_target_properties(SPIRV-Headers::SPIRV-Headers PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${SPIRV_INCLUDE_DIR}"
  )
endif()
set(SPIRV-Headers_FOUND TRUE)
EOF

printf 'VULKAN_SDK=%s\nPATH=%s\nLD_LIBRARY_PATH=%s\nCMAKE_PREFIX_PATH=%s:${CMAKE_PREFIX_PATH:-}\nSPIRV-Headers_DIR=%s\n' \
  "$VULKAN_SDK" "$PATH" "$LD_LIBRARY_PATH" "$VULKAN_SDK" "$SPIRV_HEADERS_DIR" >> "$GITHUB_ENV"
